---
resources:

jobs:

resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:sioppenh/mvn-build-demo-app.git
    branch: master

- name: build-and-verify
  plan:
  - get: source-code
    trigger: true
  - task: build-and-verify
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
        - name: source-code
      run:
        path: sh
        args:
          - -c
          - |
            echo "Calling Maven ..."
            cd source-code
            mvn verify


